Update sample.yml

diff --git a/.github/workflows/sample.yml b/.github/workflows/sample.yml
--- a/.github/workflows/sample.yml
+++ b/.github/workflows/sample.yml
@@ -73,32 +73,38 @@ jobs:
           DOCKER_BUILDKIT: 1
 
   verify_signed_image:
-      name: Verify Signed Image
-      runs-on: ubuntu-latest
+    name: Verify Signed Image
+    runs-on: ubuntu-latest
 
-      steps:
-        - name: Checkout code
-          uses: actions/checkout@v2
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-        - name: Install cosign
-          run: |
-            curl -LO https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
-            chmod +x cosign-linux-amd64
-            sudo mv cosign-linux-amd64 /usr/local/bin/cosign
+      - name: Install cosign
+        run: |
+          curl -LO https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
+          chmod +x cosign-linux-amd64
+          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
 
-        - name: Pull Docker Image
-          run: |
-            # Pull the Docker image from Docker Hub
-            docker pull sidwar/myapp:83d528afa9f3fb6f01b83e2407f8ddc39d52487d || echo "Image pull failed"
-            # Sleep for a few seconds to allow Docker Hub to synchronize
-            sleep 5
+      - name: Pull Docker Image
+        run: |
+          # Pull the Docker image from Docker Hub
+          docker pull sidwar/myapp:83d528afa9f3fb6f01b83e2407f8ddc39d52487d || echo "Image pull failed"
+          # Sleep for a few seconds to allow Docker Hub to synchronize
+          sleep 5
 
-        - name: Verify Signed Image
-          run: |
-            # Verify the signature of the Docker image using cosign
-            ls
-            cosign verify --key ./public_key.asc docker.io/sidwar/myapp:83d528afa9f3fb6f01b83e2407f8ddc39d52487d
-            
+      - name: Export Public Key
+        run: |
+          # Export the public key from the signature
+          cosign pubkey docker.io/sidwar/myapp:83d528afa9f3fb6f01b83e2407f8ddc39d52487d > extracted_pubkey.pem
+        # The exported public key will be saved in the extracted_pubkey.pem file
+
+      - name: Verify Signature
+        run: |
+          # Compare the exported public key with the provided public_key.asc file
+          diff -s public_key.asc extracted_pubkey.pem
+        # If the public keys match, it will show "Files public_key.asc and extracted_pubkey.pem are identical"
+
 
 
           
